module.exports = {
  unmentionedProbability: 1,
  origins: {
    "!hello": "#hello#",
    "!greetings": "#hello#",
    "!hey": "#hello#",
    "!sing": "#sing#",
    "!commands": "#help#",
    "!feedback": "#feedback#",
    "!song": "#sing#",
    "!twitter": "#twitter#",
    "!socials": "#socials#",
    "!music": "#sing#",
    "!teach": "#lesson#",
    "!twitch": "#twitch#",
    "!help": "#help#",
    "!giphy": "#help#",
    "!invite": "#invite#",
    "!teach": "#lesson#",
    "!credits": "#credits#",
    "!stressed": "#stress#",
    "!learn": "#lesson#",
    "!link": "#link#",
    "!site": "#link#",
    "!website": "#link#",
    ":sonicdab:": "#dab#",
    "!tpose": "#tpose#",
    "!clap": "#clap#",
    default: "#help#",
    "!babyyoda": "#babyyodameme#"
  }
};
